### ISSUE TITLE
server start success,but login error,caused by NullPointerException

### ISSUE THREAD

**Issue by PerseveranceForever** [apache/shardingsphere-elasticjob-ui#159]
latest commit : b887fad0da852d2a845d2bf7ab7a9644fcc52a54

`[ERROR] 16:02:21.128 [http-nio-8088-exec-8] o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.NullPointerException: null
        at org.apache.shardingsphere.elasticjob.lite.ui.security.UserAuthenticationService.checkUser(UserAuthenticationService.java:65)
        at org.apache.shardingsphere.elasticjob.lite.ui.security.AuthenticationFilter.handleLogin(AuthenticationFilter.java:76)
        at org.apache.shardingsphere.elasticjob.lite.ui.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)`

![image](https://user-images.githubusercontent.com/24759691/178683393-d96847c9-c1c1-4846-9e36-762b3426f043.png)

**Comment by TeslaCN** [comment]
Hi @PerseveranceForever 
The role guest has been removed.

**Comment by TeslaCN** [comment]
Hi @PerseveranceForever 
I could not reproduce this issue. I tried input wrong user or password and got 403.
![image](https://user-images.githubusercontent.com/20503072/185029083-b6062a04-3b20-4f5b-8e31-988aa00e7ba0.png)

**Comment by yequanzhuo** [comment]
I have the same problem，My operation steps are as follows：
1. git clone https://github.com/apache/shardingsphere-elasticjob-ui.git
2. cd shardingsphere-elasticjob-ui/
3. mvn clean install -Prelease -DskipTests
4. cp apache-shardingsphere-elasticjob-3.1.0-SNAPSHOT-lite-ui-bin.tar.gz /opt/apache-shardingsphere-elasticjob-3.1.0-SNAPSHOT-lite-ui-bin.tar.gz
5. cd /opt/
6. tar -zxf apache-shardingsphere-elasticjob-3.1.0-SNAPSHOT-lite-ui-bin.tar.gz
7. cd apache-shardingsphere-elasticjob-3.1.0-SNAPSHOT-lite-ui-bin/bin/
8. ./start.sh 

server start success,but login error（Neither user can login ，root ｜ guest）
![image](https://user-images.githubusercontent.com/26114870/196114930-37fc85cc-80be-4aac-8e38-3f1a0ad53c0c.png)

log content：
java.lang.NullPointerException: null
	at org.apache.shardingsphere.elasticjob.lite.ui.security.UserAuthenticationService.checkUser(UserAuthenticationService.java:65)
	at org.apache.shardingsphere.elasticjob.lite.ui.security.AuthenticationFilter.handleLogin(AuthenticationFilter.java:76)
	at org.apache.shardingsphere.elasticjob.lite.ui.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

envirment: 3.0.1

**Comment by echo20222022** [comment]
> ui

add the application.properties config:

auth.username=root
auth.password=root

and then resatart.

**Comment by TeslaCN** [comment]
Thank you @echo20222022
